# Generated by Django 4.1.1 on 2022-09-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_deepthought_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deepthought",
            name="thought_text",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
